version: '3'
services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "cpp-dev-container"
    volumes:
      - .:/home/ubuntu/
    #ports:
    #  - "5000:5000"
    network_mode: "host"
